talkable/talkable-docs

source/_static/talkable.css, source/optional.rst, source/optional/referrals_approval.rst
Learn about Talkable Fraud settings, why they are important and how to find a right Fraud Profile that works best for your site.
https://monosnap.com/file/PlXdt7mWw52NE7LYns2zs6IowbdbcW
https://monosnap.com/file/w1CCpmrrs2oO4P6QwLsVcJXKNLRPj4
=> Add referrals approval explanation documentation

source/campaigns/site_placements/invite.rst, source/saas.rst, source/samples/ecommerce/custom/post_purchase_basic.rst, source/samples/ecommerce/platform/shopify.rst, source/samples/optional/product_items.rst, source/samples/standalone/basic.rst
=> [#112902319] Campaign template 2.2 update

source/campaigns/views.rst, source/campaigns/views/advocate_rewards_confirmation.rst, source/campaigns/views/friend_rewards_paid.rst
I only separate one article into two
=> [#121663973] Feature: Add Friend Reward Paid email view

source/campaigns/editor/variables.rst, source/partials/common.rst
=> Add advocate_origin variable

source/web_hooks/reward.rst
Reverts talkable/talkable-docs#39
=> Revert "[#133759955] Feature: Add `friend_origin` to Reward webhook"

source/optional.rst, source/optional/reg_ex.rst
=> [#135783899] Create a page for regex examples at docs.talkable.com

source/campaigns/campaign_types.rst, source/partials/campaigns_for_enterprise.rst
=> Polish notice for enterprise

source/campaigns/editor/filters.rst
- [PR-5428](https://talkable.atlassian.net/browse/PR-5428)
=> Add liquid filter "squish"

source/advanced_features.rst, source/advanced_features/email_encryption.rst
http://void-docs.talkable.com/advanced_features/email_encryption.html
- [PR-6220](https://talkable.atlassian.net/browse/PR-6220)
=> [PR-6220] Email encryption

source/api_v2.rst, source/api_v2/coupons.rst
http://void-docs.talkable.com/api_v2/coupons.html
- [PR-6334](https://talkable.atlassian.net/browse/PR-6334)
=> PR-6334 Coupon <-> Email Match API

source/android_sdk/advanced.rst, source/android_sdk/upgrade.rst
Demo:
http://void-docs.talkable.com/android_sdk/upgrade.html
http://void-docs.talkable.com/android_sdk/advanced.html
=> Android-SDK: Fix bug when wrong campaign tag is passed

source/campaigns/editor/filters.rst
[PR-6140](https://talkable.atlassian.net/browse/PR-6140)
=> [PR-6140] Add locale to date filters

source/android_sdk/advanced.rst, source/android_sdk/getting_started.rst, source/android_sdk/upgrade.rst
https://github.com/talkable/talkable-android-sdk/pull/26
https://talkable.atlassian.net/browse/PR-7169
DEMO
------
http://void-docs.talkable.com/android_sdk/getting_started.html
http://void-docs.talkable.com/android_sdk/advanced.html
http://void-docs.talkable.com/android_sdk/upgrade.html
=> [PR-7169] Facebook Sharing doesn't work in default setup

source/android_sdk/advanced.rst, source/android_sdk/getting_started.rst, source/android_sdk/upgrade.rst
Demos:
http://void-docs.talkable.com/android_sdk/getting_started.html
http://void-docs.talkable.com/android_sdk/advanced.html
http://void-docs.talkable.com/android_sdk/upgrade.html
=> [PR-7044] Support multiple site slugs in Talkable Android SDK

source/integration/custom_integration.rst
Just a title change.
Jira: PR-7225
=> [PR-7225] Rename title

source/campaigns/editor/filters.rst
=> values liquid filter

source/campaigns/campaign_placements/floating_widget.rst, source/campaigns/campaign_placements/gleam.rst, source/index.rst, source/integration/demandware.rst
Add Demandware integration to docs
http://void-docs.talkable.com/integration/demandware.html
Jira: https://talkable.atlassian.net/browse/PR-7202
This request is of an urgent nature and needs to be deployed on Thursday.
Thanks.
=> [PR-7202] Add Demandware integration to docs

source/integration/custom/integration_components.rst, source/partials/for_modern_pp_js_apps.rst, source/partials/initialization.rst, source/samples/ecommerce/platform/shopify.rst
Small changes for PR-5396
more details: https://github.com/talkable/talkable/pull/2091
=> [PR-5396] async for talkable integration

source/android_sdk/upgrade.rst
- [PR-7221](https://talkable.atlassian.net/browse/PR-7221)
=> [PR-7221] Read Contacts permission issue

source/integration/shopify.rst
[PR-7824](https://talkable.atlassian.net/browse/PR-7824)
=> [PR-7824] remove signup link

source/samples/liquid/offers_show/linkedin_advanced.rst, source/samples/liquid/offers_show/linkedin_basic.rst
http://void-docs.talkable.com/campaigns/tutorials/offers_show.html?#linkedin
[![](http://proxies.talkable.com/talkable/PR-8227)](https://talkable.atlassian.net/browse/PR-8227)
=> [PR-8227] Correct linkedin claim_url interpolation

source/integration/verify.rst
http://void-docs.talkable.com/integration/verify.html
[![](http://proxies.talkable.com/talkable/PR-7736)](https://talkable.atlassian.net/browse/PR-7736)
=> [PR-7736] Integration validation popup

source/integration/magento.rst, source/integration/magento2.rst
=> Magento 2 doc corrections -> void

source/android_sdk/advanced.rst, source/android_sdk/getting_started.rst, source/android_sdk/integration/post_purchase.rst, source/android_sdk/integration/standalone.rst, source/android_sdk/upgrade.rst
[![](http://proxies.talkable.com/talkable/PR-8475)](https://talkable.atlassian.net/browse/PR-8475)
=> [PR-8475] Documentation for Callbacks in Android SDK feature

source/api_v2/people.rst
[![](http://proxies.talkable.com/talkable/PR-8690)](https://talkable.atlassian.net/browse/PR-8690)
=> [PR-8690] Add customer_id into person API payload

source/android_sdk/api.rst, source/android_sdk/integration/post_purchase.rst, source/android_sdk/upgrade.rst
[![](http://proxies.talkable.com/talkable/PR-8713)](https://talkable.atlassian.net/browse/PR-8713)
=> [PR-8713] Doc for: Add multiple coupons support for Android SDK

source/android_sdk/api.rst, source/android_sdk/integration/post_purchase.rst, source/android_sdk/upgrade.rst
[![](http://proxies.talkable.com/talkable/PR-8811)](https://talkable.atlassian.net/browse/PR-8811)
=> [PR-8811] Doc for Add product attributes support for Android SDK

source/api_v2/coupons.rst
[![](http://proxies.talkable.com/talkable/PS-4796)](https://talkable.atlassian.net/browse/PS-4796)
=> [PS-4796] Add used to coupon API docs

source/advanced_features.rst, source/advanced_features/file_encryption.rst, source/advanced_features/files_encryption.rst
http://void-docs.talkable.com/advanced_features/file_encryption.html
[![](http://proxies.talkable.com/talkable/PR-8847)](https://talkable.atlassian.net/browse/PR-8847)
=> [PR-8847] Create documentation for PGP encryption

source/campaigns/campaign_placements/floating_widget.rst, source/campaigns/campaign_placements/post_purchase.rst, source/campaigns/campaign_placements/standalone.rst, source/integration/custom/integration_components.rst, source/partials/note_sample_code.rst, source/samples/ecommerce/platform/shopify.rst, source/samples/ecommerce/platform/shopify_init_script.rst
Make site-id more unique and prominent.
http://void-docs.talkable.com/integration/custom/integration_components.html#initialization-script
[![](http://proxies.talkable.com/talkable/PR-9021)](https://talkable.atlassian.net/browse/PR-9021)
=> [PR-9021] Change your-site-id → <YOUR-TALKABLE-SITE-ID>

source/api_v2/campaigns.rst, source/api_v2/coupons.rst, source/api_v2/intro.rst, source/api_v2/metrics.rst, source/api_v2/offers.rst, source/api_v2/origins.rst, source/api_v2/people.rst, source/api_v2/referrals.rst, source/api_v2/rewards.rst, source/api_v2/shares.rst
http://void-docs.talkable.com/api_v2/intro.html#authentication
[![](http://proxies.talkable.com/talkable/PR-9035)](https://talkable.atlassian.net/browse/PR-9035)
=> [PR-9035] Accept API key in header

source/api_v2/people.rst
http://void-docs.talkable.com/api_v2/people.html
[![](http://proxies.talkable.com/talkable/PR-8873)](https://talkable.atlassian.net/browse/PR-8873)
=> [PR-8873] Doc for GDPR features

source/api_v2/shares.rst
[![](http://proxies.talkable.com/talkable/PR-8973)](https://talkable.atlassian.net/browse/PR-8973)
=> [PR-8973] Updated docs for Shares API

source/android_sdk/advanced.rst, source/android_sdk/api.rst, source/android_sdk/upgrade.rst, source/api_v2/shares.rst
[![](http://proxies.talkable.com/talkable/PR-9165)](https://talkable.atlassian.net/browse/PR-9165)
=> [PR-9165] Update Android SDK with new sharing methods for social and email share

source/api_v2/visitors.rst
=> add required param site_slug

source/android_sdk/upgrade.rst
[![](http://proxies.talkable.com/talkable/PR-9209)](https://talkable.atlassian.net/browse/PR-9209)
=> [PR-9209][Android SDK] Error 500 should be handled in Android SDK

source/api_v2/rewards.rst, source/api_v2/shares.rst
[![](http://proxies.talkable.com/talkable/PR-9275)](https://talkable.atlassian.net/browse/PR-9275)
=> [PR-9275] Reward amount is nil

source/web_hooks.rst, source/web_hooks/check_unsubscribe.rst, source/web_hooks/unsubscribe.rst
http://void-docs.talkable.com/web_hooks/unsubscribe.html
http://void-docs.talkable.com/web_hooks/check_unsubscribe.html
[![](http://proxies.talkable.com/talkable/PR-9384)](https://talkable.atlassian.net/browse/PR-9384)
=> [PR-9384] Document “unsubscribe” and “check unsubscribe” web hooks

source/android_sdk/deep_linking.rst
http://void-docs.talkable.com/android_sdk/deep_linking.html
[![](http://proxies.talkable.com/talkable/PR-9359)](https://talkable.atlassian.net/browse/PR-9359)
=> [PR-9359] Add Deep Linking support to Android SDK

source/android_sdk.rst, source/android_sdk/upgrade.rst
=> Android release 0.5.5: public doc and changelog

source/campaigns/editor/filters.rst
[![](http://proxies.talkable.com/talkable/PR-9749)](https://talkable.atlassian.net/browse/PR-9749)
=> [PR-9749] New parameters are added to barcode_image liquid filter

source/partials/coupon_as_reward.rst, source/partials/incentive_types.rst, source/web_hooks/create_coupon.rst, source/web_hooks/referral.rst, source/web_hooks/reward.rst, source/web_hooks/unsubscribe.rst
=> Re-wrote the reward webhook doc with review from Nina+Alexey+Pavao

source/android_sdk/getting_started.rst, source/android_sdk/upgrade.rst
[![](http://proxies.talkable.com/talkable/PR-9761)](https://talkable.atlassian.net/browse/PR-9761)
=> Update Android SDK installation instructions to use Maven plugin

source/web_hooks/post_share.rst
=> re-wrote the post share webhook doc

source/api_v2/origins.rst
added campaign tags to an example
[![](http://proxies.talkable.com/talkable/PR-9456)](https://talkable.atlassian.net/browse/PR-9456)
=> [PR-9456] correct an example for creating an affiliate member

source/api_v2/origins.rst, source/web_hooks/claim_signup.rst, source/web_hooks/offer_signup.rst, source/web_hooks/referral.rst, source/web_hooks/reward.rst
Docs updates for https://github.com/talkable/talkable/pull/4267
[![](http://proxies.talkable.com/talkable/PR-10134)](https://talkable.atlassian.net/browse/PR-10134)
=> [PR-10134] Add Advocate & Friend IP address to Talkable Webhooks

source/web_hooks/claim_signup.rst
[![](http://proxies.talkable.com/talkable/PR-10134)](https://talkable.atlassian.net/browse/PR-10134)
=> [PR-10134] Add IP to Friend Email Gating Webhook page

source/campaigns/views/advocate_rewards_confirmation.rst
[![](http://proxies.talkable.com/talkable/PR-7123)](https://talkable.atlassian.net/browse/PR-7123)
=> [PR-7123] Actualize Documentation for Advocate Reward Confirmation Email

source/api_v2/referrals.rst
…know what it is
http://void-docs.talkable.com/api_v2/referrals.html
[![](http://proxies.talkable.com/talkable/PS-8861)](https://talkable.atlassian.net/browse/PS-8861)
=> PS-8861 updated referrals api doc to make it easier for customers

source/api_v2/origins.rst
[![](http://proxies.talkable.com/talkable/PS-8876)](https://talkable.atlassian.net/browse/PS-8876)
=> updated the origns api doc so its easier for customers to understand

.circleci/config.yml, source/campaigns/editor/filters.rst
Related PR: https://github.com/talkable/talkable/pull/4606
[![](http://proxies.talkable.com/talkable/PR-9208)](https://talkable.atlassian.net/browse/PR-9208)
=> [PR-9208] Async liquid docs

source/android_sdk.rst, source/android_sdk/custom_deep_linking.rst, source/android_sdk/testing.rst, source/android_sdk/upgrade.rst, source/ios_sdk/custom_deep_linking.rst
http://void-docs.talkable.com/android_sdk/testing.html
=> 0.5.7 changelog + Testing page

source/campaigns/editor/filters.rst
This was requested by @iurevych
=> More async Liquid rendering docs

source/samples/ecommerce/platform/shopify_init_script.rst
http://void-docs.talkable.com/integration/shopify.html#manual-integration
demo: https://pavel2603.myshopify.com/
=> Update manual integration for shopify

source/campaigns/editor/variables.rst, source/partials/common.rst
Documented `advocate_origin.ip` and `advocate_origin.product`
http://void-docs.talkable.com/campaigns/editor/variables.html#advocate-origin
[![](http://proxies.talkable.com/talkable/PR-11195)](https://talkable.atlassian.net/browse/PR-11195)
=> [PR-11195] Document IP location and product in advocate_origin

source/campaigns/editor/filters.rst
http://void-docs.talkable.com/campaigns/editor/filters.html#events-collection
[![](http://proxies.talkable.com/talkable/PR-11358)](https://talkable.atlassian.net/browse/PR-11358)
=> [PR-11358]  liquid filter docs

source/campaigns/editor/filters.rst
http://void-docs.talkable.com/campaigns/editor/filters.html#async-rendering
[![](http://proxies.talkable.com/talkable/PR-11472)](https://talkable.atlassian.net/browse/PR-11472)
=> [PR-11472] update examples for async_rendering

source/android_sdk/integration/post_purchase.rst, source/android_sdk/integration/standalone.rst, source/android_sdk/upgrade.rst
=> Add examples for custom properties in Android SDK

source/campaigns/editor/filters.rst
https://void-docs.talkable.com/campaigns/editor/filters.html?highlight=rybbon#rybbon
[![](http://proxies.talkable.com/talkable/PR-11354)](https://talkable.atlassian.net/browse/PR-11354)
=> [PR-11354] Add `rybbon` filter

source/campaigns/editor/filters.rst
http://void-docs.talkable.com/campaigns/editor/filters.html?highlight=liquid#tremendous
[![](http://proxies.talkable.com/talkable/PR-11660)](https://talkable.atlassian.net/browse/PR-11660)
=> [PR-11660] Add `tremendous` filter

source/android_sdk/upgrade.rst
=> Android SDK 0.5.9: native email support

source/ios_sdk.rst, source/ios_sdk/advanced.rst, source/ios_sdk/api_integration.rst, source/ios_sdk/getting_started.rst, source/ios_sdk/social_sharing.rst
=> Social Sharing docs

source/campaigns/editor/filters.rst
http://void-docs.talkable.com/campaigns/editor/filters.html?highlight=filters#events-collection
[![](http://proxies.talkable.com/talkable/PR-11878)](https://talkable.atlassian.net/browse/PR-11878)
=> [PR-11878] Rename events_collection filter argument

source/campaigns/editor/filters.rst
Requested in the code review comment fix #174 
[![](http://proxies.talkable.com/talkable/PR-11878)](https://talkable.atlassian.net/browse/PR-11878)
=>  Fix events_collection filter return value description

source/android_sdk/advanced.rst
[![](http://proxies.talkable.com/talkable/PS-12860)](https://talkable.atlassian.net/browse/PS-12860)
=> [PS-12860] Better doc on direct TalkableOfferFragment usage

source/advanced_features.rst
http://void-docs.talkable.com/advanced_features.html
[![](http://proxies.talkable.com/talkable/PR-11974)](https://talkable.atlassian.net/browse/PR-11974)
=> [PR-11974] [Docs --> Advanced Features] Modify description of the Referral Tracking Methods and Advocate Personal Coupon Sharing sections

source/advanced_features/passing_custom_data.rst
=> Custom_properties real code snippets examples + rearrange the text

README.md
=> Adding deploy information

source/advanced_features/passing_custom_data.rst
http://void-docs.talkable.com/advanced_features/passing_custom_data.html
=> Custom properties real code snippets examples + rearrange the text

source/advanced_features/passing_custom_data.rst
Hide how to set and how to use sections from the table of context.
=> Fix headings in custom properties

source/advanced_features/events.rst, source/android_sdk/integration.rst, source/android_sdk/integration/event.rst, source/ios_sdk/integration.rst, source/ios_sdk/integration/event.rst
[![](http://proxies.talkable.com/talkable/PR-10805)](https://talkable.atlassian.net/browse/PR-10805)
=> [PR-10805] Update mobile SDK docs to explain how to create custom events

source/campaigns/editor/filters.rst
http://void-docs.talkable.com/campaigns/editor/filters.html?highlight=filters#date-diff
[![](http://proxies.talkable.com/talkable/PR-8776)](https://talkable.atlassian.net/browse/PR-8776)
=> [PR-8776] Document liquid date/time filters

source/ios_sdk/getting_started.rst
[![](http://proxies.talkable.com/talkable/PR-9388)](https://talkable.atlassian.net/browse/PR-9388)
=> [PR-9388] Add WhatsApp support to mobile SDKs

source/integration/custom/alternate_post_purchase.rst, source/integration/custom/integration_components.rst
[![](http://proxies.talkable.com/talkable/PR-11811)](https://talkable.atlassian.net/browse/PR-11811)
=> [PR-11811] Update docs.talkable.com to instruct how to pass traffic_source along with the affiliate_member or purchase origins

source/android_sdk/upgrade.rst
PR with code: https://github.com/talkable/android-sdk/pull/6
http://void-docs.talkable.com/android_sdk/upgrade.html
[![](http://proxies.talkable.com/talkable/PR-12076)](https://talkable.atlassian.net/browse/PR-12076)
=> [PR-12076] SDK upgrade

source/advanced_features/events.rst
https://talkable.atlassian.net/browse/PR-11559
http://void-docs.talkable.com/advanced_features/events.html
[![](http://proxies.talkable.com/talkable/PR-11559)](https://talkable.atlassian.net/browse/PR-11559)
=> [PR-11559] Optional event fields edition

source/conf.py
[![](http://proxies.talkable.com/talkable/PR-12525)](https://talkable.atlassian.net/browse/PR-12525)
=> [PR-12525] Add canonical links

source/campaigns/editor/filters.rst
http://void-docs.talkable.com/campaigns/editor/filters.html?highlight=filters#rybbon
[![](http://proxies.talkable.com/talkable/PR-11902)](https://talkable.atlassian.net/browse/PR-11902)
=> [PR-11902] Add information about usage custom value in rybbon filter

source/advanced_features/subscribing_to_events.rst
http://void-docs.talkable.com/advanced_features/subscribing_to_events.html
[![](http://proxies.talkable.com/talkable/PS-13787)](https://talkable.atlassian.net/browse/PS-13787)
=> [PS-13787] Iframe subscription feature explanation improvement

source/integration/custom/alternate_post_purchase.rst, source/integration/custom/integration_components.rst, source/samples/advanced_features/product_items.rst
http://void-docs.talkable.com/integration/custom/integration_components.html
http://void-docs.talkable.com/advanced_features/product_items.html
[![](http://proxies.talkable.com/talkable/PS-14326)](https://talkable.atlassian.net/browse/PS-14326)
=> [PS-14326] Post purchase script update + Product items passing script update

source/api_v2/metrics.rst
Related to https://github.com/talkable/talkable/pull/5797
http://void-docs.talkable.com/api_v2/metrics.html
[![](http://proxies.talkable.com/talkable/PR-12616)](https://talkable.atlassian.net/browse/PR-12616)
=> [PR-12616] Update metrics API documentation

Rakefile, source/api_v2.rst, source/api_v2/traffic_sources.rst
Related to https://github.com/talkable/talkable/pull/5795
https://void-docs.talkable.com/api_v2/traffic_sources.html
[![](http://proxies.talkable.com/talkable/PR-12630)](https://talkable.atlassian.net/browse/PR-12630)
=> [PR-12630] Add API endpoint to get all traffic sources by site

Rakefile
http://void-docs.talkable.com/ios_sdk/getting_started.html
http://void-docs.talkable.com/android_sdk/getting_started.html
[![](http://proxies.talkable.com/talkable/PR-12735)](https://talkable.atlassian.net/browse/PR-12735)
=> [PR-12735] Add rel="nofollow" to admin links

source/api_v2/metrics.rst
Related to https://github.com/talkable/talkable/pull/6027
http://void-docs.talkable.com/api_v2/metrics.html
[![](http://proxies.talkable.com/talkable/PR-12716)](https://talkable.atlassian.net/browse/PR-12716)
=> Add docs for detalize metric API

source/android_sdk/getting_started.rst, source/ios_sdk/getting_started.rst
http://void-docs.talkable.com/android_sdk/getting_started.html
=> Actualize doc for mobile SDK

source/android_sdk.rst, source/ios_sdk.rst
=> Actualize mobile SDK doc

source/campaigns/editor/filters.rst
[![](http://proxies.talkable.com/talkable/PR-13093)](https://talkable.atlassian.net/browse/PR-13093)
=> [PR-13093] Update docs after migrating site settings to apps

source/ios_sdk/getting_started.rst
=> Actualize iOS SDK doc

source/campaigns/views/notifier_offers_email.rst
https://void-docs.talkable.com/campaigns/views/notifier_offers_email.html
[![](http://proxies.talkable.com/talkable/PR-13310)](https://talkable.atlassian.net/browse/PR-13310)
=> [PR-13310] Remove copy from web page

source/api_v2/offers.rst, source/api_v2/origins.rst
http://void-docs.talkable.com/api_v2/offers.html#example
http://void-docs.talkable.com/api_v2/origins.html#create-an-affiliate-member-and-target-a-campaign
=> Update API V2 offers response

source/web_hooks.rst
http://void-docs.talkable.com/web_hooks.html#talkable_ips
=> Add ID to Talkable IPs section

source/android_sdk/upgrade.rst
[![](http://proxies.talkable.com/talkable/PR-13466)](https://talkable.atlassian.net/browse/PR-13466)
[![](http://proxies.talkable.com/talkable/PR-13440)](https://talkable.atlassian.net/browse/PR-13440)
=> Update Android SDK version

source/advanced_features/customer_service_portal/terminology.rst, source/advanced_features/referrals_approval.rst
http://void-docs.talkable.com/advanced_features/referrals_approval.html
[![](http://proxies.talkable.com/talkable/PR-13476)](https://talkable.atlassian.net/browse/PR-13476)
=> [PR-13476] Update referrals_approval

source/advanced_features/customer_service_portal/terminology.rst, source/web_hooks/referral.rst
[![](http://proxies.talkable.com/talkable/PR-13478)](https://talkable.atlassian.net/browse/PR-13478)
=> [PR-13478] Remove 'Unblocked' term from docs

source/partials/note_sample_integration.rst
[![](http://proxies.talkable.com/talkable/PS-16310)](https://talkable.atlassian.net/browse/PS-16310)
=> Explicitly set https as Shopify library link

source/android_sdk/custom_deep_linking.rst, source/api_v2/flow.rst, source/ios_sdk/custom_deep_linking.rst
related to https://github.com/talkable/talkable/pull/6521
[![](http://proxies.talkable.com/talkable/PR-13782)](https://talkable.atlassian.net/browse/PR-13782)
=> [PR-13782] Change talkable_visitor_uuid to tkbl_cvuuid

source/advanced_features/track_methods.rst
http://void-docs.talkable.com/advanced_features/track_methods.html
[![](http://proxies.talkable.com/talkable/PR-13789)](https://talkable.atlassian.net/browse/PR-13789)
=> [PR-13789] Add Force Manually Generated referrals to docs

source/ios_sdk/getting_started.rst
[![](http://proxies.talkable.com/talkable/PR-13130)](https://talkable.atlassian.net/browse/PR-13130)
=> Add info about CocoaPods integration for iOS SDK

source/web_hooks/reward.rst
Related to https://github.com/talkable/talkable/pull/6851
http://void-docs.talkable.com/web_hooks/reward.html
[![](http://proxies.talkable.com/talkable/PR-13851)](https://talkable.atlassian.net/browse/PR-13851)
=> [PR-13851] Add incentive identifier to reward webhook

source/_templates/layout.html
=> Load fonts over https

source/_static/talkable.css
https://void-docs.talkable.com/integration/demandware.html
before:
after:
=> Fix styles for note block

source/_static/talkable.css
Fix for: https://github.com/talkable/talkable-docs/pull/224#issuecomment-722333176
=> Polish reset styles

source/advanced_features.rst, source/advanced_features/params_encryption.rst
Docs update for https://github.com/talkable/talkable/pull/6883
[![](http://proxies.talkable.com/talkable/PR-14653)](https://talkable.atlassian.net/browse/PR-14653)
=> [PR-14653] Add docs with examples of PCP encryption

source/campaigns/editor/filters.rst
Filter added in [#6980](https://github.com/talkable/talkable/pull/6980).
http://void-docs.talkable.com/campaigns/editor/filters.html?highlight=filter#pluralize
[![](http://proxies.talkable.com/talkable/PR-14214)](https://talkable.atlassian.net/browse/PR-14214)
=> [PR-14214] Add 'pluralize' liquid filter

source/campaigns/editor/videos.rst
Before:
https://docs.talkable.com/campaigns/editor/videos.html?highlight=videos
After:
https://deploy-preview-231--talkable-docs.netlify.app/campaigns/editor/videos.html?highlight=videos
=> Fix video links

source/partials/origin_fields.rst, source/web_hooks/event.rst, source/web_hooks/post_share.rst, source/web_hooks/referral.rst, source/web_hooks/reward.rst
Docs for https://github.com/talkable/talkable/pull/7023
http://void-docs.talkable.com/web_hooks.html
[![](http://proxies.talkable.com/talkable/PR-14714)](https://talkable.atlassian.net/browse/PR-14714)
=> [PR-14714] Add traffic_source into Referral/Event webhook

source/ios_sdk/getting_started.rst
Related to https://github.com/talkable/ios-sdk/pull/11
https://deploy-preview-233--talkable-docs.netlify.app/ios_sdk/getting_started.html
[![](http://proxies.talkable.com/talkable/PR-14360)](https://talkable.atlassian.net/browse/PR-14360)
=> [PR-14360] update docs

source/integration/shopify.rst
https://deploy-preview-232--talkable-docs.netlify.app/integration/shopify.html
[![](http://proxies.talkable.com/talkable/PR-14389)](https://talkable.atlassian.net/browse/PR-14389)
=> [PR-14389] Compose integration docs updates

source/_templates/search.html
our search doesn’t work since the 3.4.0 version
https://deploy-preview-237--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-15246)](https://talkable.atlassian.net/browse/PR-15246)
=> [PR-15246] Search is not working

source/api_v2/campaigns.rst, source/api_v2/coupons.rst, source/campaigns.rst
https://github.com/talkable/talkable/pull/6589
[![](http://proxies.talkable.com/talkable/PR-13910)](https://talkable.atlassian.net/browse/PR-13910)
=> [PR-13910] update api_v2/campaigns response

source/api_v2/people.rst, source/api_v2/referrals.rst
http://void-docs.talkable.com/api_v2/people.html#get-friends-referred-by-advocate
[![](http://proxies.talkable.com/talkable/PR-15653)](https://talkable.atlassian.net/browse/PR-15653)
=> [PR-15653] Add fraud fields to ApiV2::ReferralSerializer

source/api_v2.rst, source/api_v2/origins.rst, source/api_v2/refunds.rst
Code: https://github.com/talkable/talkable/pull/7307
https://deploy-preview-239--talkable-docs.netlify.app/api_v2/refunds.html
[![](http://proxies.talkable.com/talkable/PR-15427)](https://talkable.atlassian.net/browse/PR-15427)
=> [PR-15427] Purchase refunds

source/partials/reward_fields.rst, source/web_hooks/referral.rst
http://void-docs.talkable.com/web_hooks/referral.html
[![](http://proxies.talkable.com/talkable/PR-15817)](https://talkable.atlassian.net/browse/PR-15817)
=> [PR-15817] Redo Referral webhook description

source/api_v2.rst, source/api_v2/loyalty.rst, source/api_v2/loyalty_members.rst
Related to https://github.com/talkable/talkable/pull/7511.
https://deploy-preview-244--talkable-docs.netlify.app/api_v2/loyalty_members.html
[![](http://proxies.talkable.com/talkable/PR-16036)](https://talkable.atlassian.net/browse/PR-16036)
[![](http://proxies.talkable.com/talkable/PR-16064)](https://talkable.atlassian.net/browse/PR-16064)
=> [PR-16036 PR-16064] Loyalty points API

source/api_v2/loyalty_members.rst
http://void-docs.talkable.com/api_v2/loyalty_members.html
[![](http://proxies.talkable.com/talkable/PR-15975)](https://talkable.atlassian.net/browse/PR-15975)
=> [PR-15975] Loyalty members report redesign - Adjust points manually (BE)

source/api_v2/loyalty_members.rst
Documents https://github.com/talkable/talkable/pull/7589.
http://void-docs.talkable.com/api_v2/loyalty_members.html
[![](http://proxies.talkable.com/talkable/PR-16200)](https://talkable.atlassian.net/browse/PR-16200)
=> [PR-16200] Loyalty Custom property API

source/web_hooks/check_unsubscribe.rst, source/web_hooks/claim_signup.rst, source/web_hooks/event.rst, source/web_hooks/offer_signup.rst, source/web_hooks/referral.rst, source/web_hooks/reward.rst, source/web_hooks/unsubscribe.rst
Leftover for https://github.com/talkable/talkable/pull/7616
http://void-docs.talkable.com/web_hooks/event.html
[![](http://proxies.talkable.com/talkable/PR-16386)](https://talkable.atlassian.net/browse/PR-16386)
=> [PR-16386] Add loyalty info to webhook person payload

source/advanced_features.rst, source/advanced_features/params_encryption.rst, source/advanced_features/passing_custom_data.rst, source/partials/common.rst
http://void-docs.talkable.com/advanced_features/params_encryption.html
http://void-docs.talkable.com/advanced_features/passing_custom_data.html#advanced-features-passing-custom-data
[![](http://proxies.talkable.com/talkable/PR-16241)](https://talkable.atlassian.net/browse/PR-16241)
=> [PR-16241] [Loyalty] Support email and custom property encryption for all loyalty campaigns

source/advanced_features/shopify_coupons_auto_sync.rst
Leftover for https://github.com/talkable/talkable/pull/7923
https://deploy-preview-259--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-17061)](https://talkable.atlassian.net/browse/PR-17061)
=> [PR-17061] Fix logic of coupon list update when auto_sync_enabled

source/integration/ecommerce_platforms/demandware.rst, source/integration/ecommerce_platforms/magento.rst, source/integration/ecommerce_platforms/shopify.rst, source/integration/loyalty.rst, source/integration/loyalty/manual_shopify_integration.rst
https://deploy-preview-257--talkable-docs.netlify.app/
https://void-docs.talkable.com/integration/loyalty/manual_shopify_integration.html
[![](http://proxies.talkable.com/talkable/PR-17179)](https://talkable.atlassian.net/browse/PR-17179)
=> [PR-17179][Docs] Add Loyalty Manual Shopify integration to docs

source/partials/origin_fields.rst, source/partials/person_fields.rst, source/web_hooks/post_share.rst
https://void-docs.talkable.com/web_hooks/post_share.html
[![](http://proxies.talkable.com/talkable/PR-17382)](https://talkable.atlassian.net/browse/PR-17382)
=> [PR-17382] Add sharer_info to Post-Share Webhook

source/advanced_features/events.rst, source/integration/custom/integration_components.rst
https://deploy-preview-262--talkable-docs.netlify.app/advanced_features/events.html#available-properties
https://deploy-preview-262--talkable-docs.netlify.app/integration/custom/integration_components.html#post-purchase-script-notes
[![](http://proxies.talkable.com/talkable/PR-16667)](https://talkable.atlassian.net/browse/PR-16667)
=> [PR-16667] Support encryption for origin params

source/campaigns/editor/filters.rst
Related to https://github.com/talkable/talkable/pull/8266.
https://deploy-preview-267--talkable-docs.netlify.app/campaigns/editor/filters.html#update-query
[![](http://proxies.talkable.com/talkable/PR-17824)](https://talkable.atlassian.net/browse/PR-17824)
=> [PR-17824] Liquid filter 'update_query'

source/integration/loyalty/auto_enrollment.rst, source/integration/loyalty/integration_components.rst
Main PR [#8357](https://github.com/talkable/talkable/pull/8357)
https://deploy-preview-269--talkable-docs.netlify.app/integration/loyalty/auto_enrollment.html
https://deploy-preview-269--talkable-docs.netlify.app/integration/loyalty/integration_components.html
[![](http://proxies.talkable.com/talkable/PR-17865)](https://talkable.atlassian.net/browse/PR-17865)
=> [PR-17865] Add customer_id to loyalty docs

source/integration/ecommerce_platforms/shopify.rst
https://deploy-preview-271--talkable-docs.netlify.app/integration/ecommerce_platforms/shopify.html#manual-integration
[![](http://proxies.talkable.com/talkable/PR-18100)](https://talkable.atlassian.net/browse/PR-18100)
=> [PR-18100] Update setup Shopify instructions

source/advanced_features/events.rst, source/integration/custom/alternate_post_purchase.rst, source/integration/custom/integration_components.rst, source/samples/advanced_features/product_items.rst, source/web_hooks/event.rst
Main PR [#8364](https://github.com/talkable/talkable/pull/8364)
https://deploy-preview-270--talkable-docs.netlify.app/integration/custom/alternate_post_purchase.html?highlight=currency%20iso_code
https://deploy-preview-270--talkable-docs.netlify.app/web_hooks/event.html?highlight=currency%20iso_code
https://deploy-preview-270--talkable-docs.netlify.app/advanced_features/product_items.html?highlight=currency%20iso_code
https://deploy-preview-270--talkable-docs.netlify.app/advanced_features/events.html?highlight=currency%20iso_code
https://deploy-preview-270--talkable-docs.netlify.app/integration/custom/integration_components.html?highlight=currency%20iso_code
[![](http://proxies.talkable.com/talkable/PR-18042)](https://talkable.atlassian.net/browse/PR-18042)
=> [PR-18042] Add currency as required attribute for multi-currency sites

source/advanced_features.rst, source/advanced_features/shopify_purchase_syncing.rst, source/advanced_features/shopify_purchases_syncing.rst
Feature PR: https://github.com/talkable/talkable/pull/8400
https://deploy-preview-273--talkable-docs.netlify.app/advanced_features/shopify_purchase_syncing.html
[![](http://proxies.talkable.com/talkable/PR-18273)](https://talkable.atlassian.net/browse/PR-18273)
=> [PR-18273] Shopify Purchase Syncing doc

source/android_sdk/integration/post_purchase.rst, source/android_sdk/integration/standalone.rst, source/ios_sdk/advanced.rst, source/ios_sdk/api_integration.rst, source/ios_sdk/getting_started.rst, source/ios_sdk/integration/event.rst, source/ios_sdk/integration/post_purchase.rst, source/ios_sdk/integration/standalone.rst, source/ios_sdk/social_sharing.rst
Documentation update for https://github.com/talkable/ios-sdk/pull/16
https://deploy-preview-275--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-16730)](https://talkable.atlassian.net/browse/PR-16730)
=> [PR-16730] SPM distribution documentation for iOS SDK and polishing

source/integration/ecommerce_platforms/shopify.rst, source/integration/loyalty.rst, source/integration/loyalty/shopify_integration.rst
https://deploy-preview-276--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-17032)](https://talkable.atlassian.net/browse/PR-17032)
=> [PR-17032] Update Loyalty Shopify integration docs

source/campaigns/editor/variables.rst
[![](http://proxies.talkable.com/talkable/PR-18259)](https://talkable.atlassian.net/browse/PR-18259)
=> [PR-18259]: Update Docs for variables

source/partials/campaign_fields.rst, source/partials/origin_fields.rst, source/partials/person_fields.rst, source/web_hooks/claim_signup.rst, source/web_hooks/create_coupon.rst, source/web_hooks/post_share.rst, source/web_hooks/referral.rst, source/web_hooks/reward.rst
https://void-docs.talkable.com/web_hooks.html
[![](http://proxies.talkable.com/talkable/PR-18309)](https://talkable.atlassian.net/browse/PR-18309)
=> [PR-18309] Actualize Webhook sample payloads

source/ios_sdk/advanced.rst, source/ios_sdk/getting_started.rst
iOS SDK changes: https://github.com/talkable/ios-sdk/pull/18
https://deploy-preview-277--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-18578)](https://talkable.atlassian.net/browse/PR-18578)
=> [PR-18578] Update iOS SDK documentation for v1.4.14

source/android_sdk/advanced.rst, source/android_sdk/getting_started.rst, source/android_sdk/testing.rst
https://deploy-preview-284--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-18465)](https://talkable.atlassian.net/browse/PR-18465)
=> [PR-18465] Update documentation for Site ID

source/samples/ecommerce/platform/shopify.rst
Main PR [#8694](https://github.com/talkable/talkable/pull/8694)
https://deploy-preview-285--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-18719)](https://talkable.atlassian.net/browse/PR-18719)
=> [PR-18719] Add currency_iso_code to Shopify Manual Integration

source/api_v2/intro.rst
https://void-docs.talkable.com/api_v2/intro.html#throttling
[![](http://proxies.talkable.com/talkable/PR-19068)](https://talkable.atlassian.net/browse/PR-19068)
=> [PR-19068] [Documentation] Explain throttling in API documentation

source/advanced_features.rst, source/advanced_features/coupons.rst
https://deploy-preview-293--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-18923)](https://talkable.atlassian.net/browse/PR-18923)
=> [PR-18923] Add coupon validation information

source/samples/ecommerce/platform/shopify.rst
https://deploy-preview-300--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-19091)](https://talkable.atlassian.net/browse/PR-19091)
=> Shopify Manual Integration Use presentment_currency

source/_templates/search.html
https://deploy-preview-301--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-19465)](https://talkable.atlassian.net/browse/PR-19465)
=> [PR-19465] Fix search

source/ios_sdk/getting_started.rst
SDK update: https://github.com/talkable/ios-sdk/pull/21
https://deploy-preview-302--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-19365)](https://talkable.atlassian.net/browse/PR-19365)
=> [PR-19365] Actualize iOS version

source/android_sdk/getting_started.rst, source/android_sdk/upgrade.rst
https://deploy-preview-309--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-19613)](https://talkable.atlassian.net/browse/PR-19613)
=> [PR-19613] Android SDK 0.5.12 update

source/ios_sdk/advanced.rst, source/ios_sdk/api_integration.rst, source/ios_sdk/getting_started.rst
SDK update: https://github.com/talkable/ios-sdk/pull/22
https://deploy-preview-308--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PR-16122)](https://talkable.atlassian.net/browse/PR-16122)
=> [PR-16122] Update docs for iOS SDK 1.5.1

source/integration/ecommerce_platforms/shopify.rst
https://deploy-preview-310--talkable-docs.netlify.app/
https://deploy-preview-310--talkable-docs.netlify.app/integration/ecommerce_platforms/shopify.html
[![](http://proxies.talkable.com/talkable/PR-19747)](https://talkable.atlassian.net/browse/PR-19747)
=> [PR-19747] Update Shopify integration doc

source/advanced_features/events.rst
https://deploy-preview-317--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PS-29704)](https://talkable.atlassian.net/browse/PS-29704)
=> [PS-29704] Add JS library link to event docs

source/advanced_features/shopify_purchase_syncing.rst, source/samples/ecommerce/platform/shopify.rst
https://void-docs.talkable.com/integration/ecommerce_platforms/shopify.html#manual-integration
https://void-docs.talkable.com/advanced_features/shopify_purchase_syncing.html#shopify-webhook-payload-and-talkable-purchase-attributes-mapping
[![](http://proxies.talkable.com/talkable/PR-20712)](https://talkable.atlassian.net/browse/PR-20712)
=> [PR-20712] Update Shopify subtotal tracking logic

source/integration/custom/cookies.rst, source/integration/custom_integration.rst
[![](http://proxies.talkable.com/talkable/PR-20586)](https://talkable.atlassian.net/browse/PR-20586)
=> [PR-20586] documentation for cookies

source/campaigns/editor/filters.rst
Docs for https://github.com/talkable/talkable/pull/9533
https://void-docs.talkable.com/campaigns/editor/filters.html#events-collection
https://deploy-preview-321--talkable-docs.netlify.app/
[![](http://proxies.talkable.com/talkable/PS-30101)](https://talkable.atlassian.net/browse/PS-30101)
=> [PS-30101] Add refunded field to events_collection filter

source/integration/custom/integration_tag_manager.rst
https://void-docs.talkable.com/integration/custom/integration_tag_manager.html
[![](http://proxies.talkable.com/talkable/PR-20974)](https://talkable.atlassian.net/browse/PR-20974)
=> [PR-20974] Add information about GTM performance

source/advanced_features.rst, source/advanced_features/multi_currency.rst
https://void-docs.talkable.com/advanced_features/multi_currency.html#passing-visitor-s-preferred-currency
[![](http://proxies.talkable.com/talkable/PR-22228)](https://talkable.atlassian.net/browse/PR-22228)
=> [PR-22228] Describe how to pass preferred currency via JS integration

source/advanced_features/params_encryption.rst
[![](http://proxies.talkable.com/talkable/PR-22059)](https://talkable.atlassian.net/browse/PR-22059)
=> Add recommendation to use OAEP

source/email_marketing_and_automation/custom_app.rst
[![](http://proxies.talkable.com/talkable/PR-22911)](https://talkable.atlassian.net/browse/PR-22911)
=> [PR-22911] [Docs Talkable] Update contents in the article

source/campaigns/editor/filters.rst
Describes filters that were added in talkable/talkable#10130.
https://void-docs.talkable.com/campaigns/editor/filters.html#new-array
[![](http://proxies.talkable.com/talkable/PR-22826)](https://talkable.atlassian.net/browse/PR-22826)
=> [PR-22826] Liquid filters for arrays and hashes

source/campaigns/editor/filters.rst
[![](http://proxies.talkable.com/talkable/PR-23345)](https://talkable.atlassian.net/browse/PR-23345)
=> [PR-23345] [Docs] Replace "ru" as locale example

source/api_v2/flow.rst
https://void-docs.talkable.com/api_v2/flow.html
[![](http://proxies.talkable.com/talkable/PR-23306)](https://talkable.atlassian.net/browse/PR-23306)
=> [PR-23306] Add a note about offers_shown metric and API V2

source/advanced_features/shopify_coupons_auto_sync.rst
https://void-docs.talkable.com/advanced_features/shopify_coupons_auto_sync.html
[![](http://proxies.talkable.com/talkable/PR-23258)](https://talkable.atlassian.net/browse/PR-23258)
=> [PR-23258] Document PriceRule allocation_method requirements

deploy/Jenkinsfile
https://talkable.slack.com/archives/C7ULQPU2J/p1739422011569189
=> Add Slack notifications

source/integration/ecommerce_platforms/shopify.rst
https://docs.bastion.talkable.com/integration/ecommerce_platforms/shopify/
[![](http://proxies.talkable.com/talkable/PR-23893)](https://talkable.atlassian.net/browse/PR-23893)
=> [PR-23893] Add remark about Github integration and theme to docs

README.md, docker-compose.yml
* Proper instrcution have been added
* Nginx container "restart unless stopped" directive have been addeded to keep the nginx up if docker restarts
[![](http://proxies.talkable.com/talkable/PR-24073)](https://talkable.atlassian.net/browse/PR-24073)
=> [PR-24073] Add local env removal instructions to Readme

source/campaigns/editor/filters.rst
Related to talkable/talkable#10496.
https://docs.bastion.talkable.com/campaigns/editor/filters/#class-names
[![](http://proxies.talkable.com/talkable/PR-24082)](https://talkable.atlassian.net/browse/PR-24082)
=> [PR-24082] Add Liquid filter 'class_names'

source/_static/talkable.css
[![](http://proxies.talkable.com/talkable/PR-23990)](https://talkable.atlassian.net/browse/PR-23990)
=> [PR-23990] [Docs] Fix side menu

source/campaigns/editor/filters.rst
[![](http://proxies.talkable.com/talkable/PR-23182)](https://talkable.atlassian.net/browse/PR-23182)
=> [PR-23182] Add description for qr_code liquid filter

source/advanced_features/track_methods.rst
https://docs.bastion.talkable.com/advanced_features/track_methods/
[![](http://proxies.talkable.com/talkable/PR-23720)](https://talkable.atlassian.net/browse/PR-23720)
=> [PR-23720] Support referral attribution, testing, and handle fraud by phone number

source/campaigns/views/notifier_offers_email.rst
[![](http://proxies.talkable.com/talkable/PR-24967)](https://talkable.atlassian.net/browse/PR-24967)
=> [PR-24967] Fix 'Email sending conditions' documentation typo
